on:
  push:
    branches:
      - martin

name: Robot builder (martin branch)
jobs:
  build:
    runs-on: ubuntu-latest
    environment: javacard.pro
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add host key
        if: github.event_name != 'pull_request'
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Run Maven
        run: ./mvnw -T1C -B -U verify
      - name: Deploy snapshot
        if: github.event_name != 'pull_request'
        run: ./mvnw -B -U deploy
